apiVersion: batch/v1
kind: Job
metadata:
  name: baseline-job
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: baseline
        image: ghcr.io/nathanielnat1993/cloud-computing-project:latest
        command: ["python", "src/main.py", "--mode", "baseline"]
        volumeMounts:
        - mountPath: /project/data
          name: project-storage
        resources:
          requests:
            cpu: "1"
            memory: "12Gi"
          limits:
            cpu: "2"
            memory: "24Gi"
      volumes:
      - name: project-storage
        persistentVolumeClaim:
          claimName: naaxk6-pvc

