apiVersion: batch/v1
kind: Job
metadata:
  name: finetune-job
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      terminationGracePeriodSeconds: 600
      restartPolicy: Never
      containers:
      - name: finetune
        image: ghcr.io/nathanielnat1993/cloud-computing-project:latest
        imagePullPolicy: Always
        command: ["python", "/project/src/main.py", "--mode", "finetune", "--data_path", "/project/storage/data"]
        resources:
          requests:
            cpu: "2"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "32Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /project/storage
          name: project-storage
      volumes:
      - name: project-storage
        persistentVolumeClaim:
          claimName: naaxk6-pvc
