apiVersion: v1
kind: Pod
metadata:
  name: inspect-pvc
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  restartPolicy: Never
  containers:
  - name: inspector
    image: ubuntu:22.04
    command: ["bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: project-storage
      mountPath: /data
  volumes:
  - name: project-storage
    persistentVolumeClaim:
      claimName: naaxk6-pvc
