apiVersion: v1
kind: Pod
metadata:
  name: pvc-explorer
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  containers:
  - name: explorer
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /data
      name: project-storage
  volumes:
  - name: project-storage
    persistentVolumeClaim:
      claimName: naaxk6-pvc
