apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 15a9527cd663ea4774ca8690a1d56868555559e2508d3825e8e1678a7532ef71
    cni.projectcalico.org/podIP: ""
    cni.projectcalico.org/podIPs: ""
  creationTimestamp: "2025-11-23T03:13:05Z"
  generateName: baseline-job-
  labels:
    batch.kubernetes.io/controller-uid: d6037657-dcd4-4cd5-b618-737bb26078d4
    batch.kubernetes.io/job-name: baseline-job
    controller-uid: d6037657-dcd4-4cd5-b618-737bb26078d4
    job-name: baseline-job
  name: baseline-job-2cjjv
  namespace: gp-engine-mizzou-dsa-cloud
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: baseline-job
    uid: d6037657-dcd4-4cd5-b618-737bb26078d4
  resourceVersion: "11947454626"
  uid: 5e88e703-8710-46c4-90d5-fe98228b987b
spec:
  containers:
  - command:
    - python
    - src/main.py
    - --mode
    - baseline
    image: ghcr.io/nathanielnat1993/cloud-computing-project:latest
    imagePullPolicy: Always
    name: baseline
    resources:
      limits:
        cpu: "2"
        memory: 24Gi
        nvidia.com/gpu: "1"
      requests:
        cpu: "1"
        memory: 12Gi
        nvidia.com/gpu: "1"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /project/data
      name: project-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-psh9q
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-haosu-03.sdsc.optiputer.net
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: PreferNoSchedule
    key: nvidia.com/gpu
    operator: Exists
  volumes:
  - name: project-storage
    persistentVolumeClaim:
      claimName: naaxk6-pvc
  - name: kube-api-access-psh9q
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-11-23T03:13:18Z"
    status: "False"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-11-23T03:13:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-11-23T03:13:16Z"
    reason: PodFailed
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-11-23T03:13:16Z"
    reason: PodFailed
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-11-23T03:13:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e5c158368d9a2d240162ff55578a038529786ba69c0a178647a1c1295836c950
    image: ghcr.io/nathanielnat1993/cloud-computing-project:latest
    imageID: ghcr.io/nathanielnat1993/cloud-computing-project@sha256:2f7b548099dcaf1250d8f94b3d738523525576ec558ca20c59174eb346191965
    lastState: {}
    name: baseline
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://e5c158368d9a2d240162ff55578a038529786ba69c0a178647a1c1295836c950
        exitCode: 1
        finishedAt: "2025-11-23T03:13:15Z"
        reason: Error
        startedAt: "2025-11-23T03:13:11Z"
    volumeMounts:
    - mountPath: /project/data
      name: project-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-psh9q
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 67.58.63.5
  hostIPs:
  - ip: 67.58.63.5
  phase: Failed
  podIP: 10.244.6.87
  podIPs:
  - ip: 10.244.6.87
  - ip: fdf0:17b3:c3ec:1f79:10:0:5:5af8
  qosClass: Burstable
  startTime: "2025-11-23T03:13:05Z"
