apiVersion: v1
kind: Pod
metadata:
  name: pvc-access
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  containers:
  - name: pvc-shell
    image: busybox
    command: ["sleep", "360000"]
    volumeMounts:
    - name: project-storage
      mountPath: /project
  volumes:
  - name: project-storage
    persistentVolumeClaim:
      claimName: naaxk6-pvc