apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naaxk6-pvc
  namespace: gp-engine-mizzou-dsa-cloud
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi